### ISSUE TITLE
Capacity Expansion

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#125]
## Problem description

We currently only allow investment in capacity at the zeroth timestep. This means that we can't model capacity expansion, or delayed capacity investment. 

Two methods I can think of (will add more as discussion leads to them):

1. Allow setting a timestep for delayed investment, setting all dispatch constraints (e.g. `carrier_prod <= energy_cap` to zero until that timestep. Setting several timesteps could allow expansion to take place at those timesteps. This could also work with `datesteps` (an existing dimension for inter-cluster storage).

2. Less flexible than method 1, we could introduce another time dimension: `yearsteps`. This assumes that delayed capacity investment & capacity expansion would take place on an annual basis.

Either way, could we make it work with time aggregation methods?

## Steps to introduce functionality

- [ ] Decide on method of implementation
- [ ] Work out how to combine it with time aggregation methods (particularly time clustering)

**Comment by FirstWorldSlardar** [comment]
Just to be sure, your first point would look like below in the techs config:
```yaml
a_tech:
    constraints:
        energy_cap: X
        capacity_expansion: file=data.csv
```
and in data.csv:
```csv
,Loc1,Loc2, ..
2010, 0, 1 ..
2011, 0, 0 ..
2013, 0, 0 ..
2014, 1, 1 ..
2015, 0, 0
```

And it would mean that in Loc2 the energy_cap is 2X and in Loc1 it is X in 2014 ?

**Comment by brynpickering** [comment]
I'd stick with `energy_cap_equals`/`max`/`min`, instead of just `energy_cap`. That way when it hits one of the points in the file it either has to have its maximum available capacity increased, or it has to be equal to that capacity. I like the idea of having it in a csv file, with multiple options for resolution.

For instance, an hourly model could still have:

```csv
,Loc1,Loc2, ..
2010, 0, 1 ..
2011, 0, 0 ..
2013, 0, 0 ..
2014, 1, 1 ..
2015, 0, 0
```
Which says that although the model is hourly, the capacity expansion information changes annually (assuming first timestep of that year)

**Comment by brynpickering** [comment]
To get a simple version of this working, we need:

1. to add 'datesteps' or 'expansionsteps' or 'yearsteps' to the dimensions over which the capacity decision variables are indexed (see `calliope.backend.pyomo.variables.py`).

2. to update the capacity constraints (`calliope.backend.pyomo.constraints.capacity.py`) to include this new dimension and to include the scripts to consider the possibility of expansion.

3. to work out how to make it conditional on someone including capacity expansion. I.e. it should take no longer to run the model than before, if someone chooses to not include expansion.

**Comment by brynpickering** [comment]
I've started working on this: https://github.com/calliope-project/calliope/tree/cap_expansion

Still need:

1. a lookup array to get the `expansionstep` given a `timestep`
2. use the lookup array from 1. in the dispatch constraints
3. to manage `expansionsteps` in plotting
4. on subsetting time, if t = 0 is not one of the `expansionsteps` then take the value associated with the previous `expansionstep` as the value at t = 0. e.g. if expansionsteps are:
```
2005-01-01,100
2005-07-01,150
2005-07-02,180
2005-07-04,200
2005-07-09,250
2005-07-12,300
2005-07-15,350
```
and subset_time is ['2005-06-01', '2005-07-05'], currently we end up with `expansionsteps`:
```
2005-07-01,150
2005-07-02,180
2005-07-04,200
```
but we should actually have:
```
2005-06-01,100
2005-07-01,150
2005-07-02,180
2005-07-04,200
```

5. Work out how to make the model simpler when not using capacity expansion in most cases. Currently, if you include `expansionsteps` on any capacity, all capacity constraints will consider `expansionsteps`. I imagine everything will take longer as a result of this. We should probably then make our sets even more dense (e.g. from loc_techs, expansionsteps to loc_techs_expansionsteps))

**Comment by sjpfenninger** [comment]
@brynpickering @FirstWorldSlardar I think it would be great to advance on this! But it might make sense to think clearly about different possible use cases first — i.e. what kinds of problems this functionality should cover — so that we can make sure it doesn't have to be re-designed later.

The current proposal of allowing constraints like energy_cap_max to be indexed over time but with a lower resolution (e.g. annual) seems sensible.

A couple of points that come to mind:

* Assuming a model of capacity expansion from now through 2050 in something like 5-year steps, it would probably be ok or even desirable to use the same weather year for each investment decision time period. So one could "re-use" that data, probably clustered/resampled, but add a longer term investment time dimension, i.e. `expansionstep`, on top.
* One would probably want to track vintage / lifetime of all assets, so when an existing or newly built plant reaches its EOL, it its capacity goes back to 0, and the model makes new investments. While the initial implementation might skip that, there should at least be a path to implement this later.
* Again possibly later, there might be an entire new set of constraints to make it easier to model deployment, like setting a min/max/fixed deployment rate rather than a specific capacity constraint in each `expansionstep`.

**Comment by b-jesse** [comment]
Although the subject is somewhat pointed out, I would like to continue here. Unfortunately I don't have much experience in programming LP problems yet and my knowledge of Pyomo is limited (so far I only worked with calliope). 

Since @sjpfenninger asked about the possibilities of capacity expansion, I would like to explain briefly what I think it is:

Perfect Forsight:
The time period to be optimized can extend beyond the lifetime of technologies. The result shows how much capacity should be added of which technology at which point in time in the considered period in order to maximize/minimize the target function. The solver has to consider the whole time period. 

Considerations:
Meaning that time series (such as consumption, capacity factors, etc.) are necessary for the whole time period. 
If you calculate every year, the calculation time grows quite fast.
Allow extensions at any time or only at the beginning of a year? (won't it then become a MILP?)
The remaining lifetime of each capacity would have to be tracked and stored.
How compatible with clustering

Extras that could be added later:
Starting conditions, such as available capacities and remaining service life
Only allow certain amounts of capacity to be built (won't it then become a MILP?)
Premature dismantling

Myopic forsight:
Actually you only need everything perfect forsight has and starting conditions. The rest is just a bunch of pre- and post-processing. Or did I miss something.

These are the applications I have in mind for capacity expansion. The next step would be to find out if there are any papers on this kind of capacity expansion and how to implement it. Has anyone ever found anything about this?

I hope that I was able to explain everything in an understandable way.

**Comment by brynpickering** [comment]
Capacity expansion is now possible using the [new math syntax](https://calliope.readthedocs.io/en/latest/user_defined_math). We have implemented pathways / capacity expansion math with this new syntax. You can check it out in our [dedicated pathways repository](https://github.com/calliope-project/calliope-pathways). We'll be using this repo to further experiment with the best mathematical formulation.
