### ISSUE TITLE
energy_cap_max default value

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#161]
## Problem description

There seems to be an inconsistency with the `energy_cap_max` value in the documentation. On one hand, the documentation states that one of `[energy_cap_equals, energy_cap_max, energy_cap_per_unit]` is a required attribute (which _actually_ is the case). On the other hand though, it states that `energy_cap_max` has a default value of `inf`. Both statements can be found in the "Listing of configuration options".

Two possible solutions:

1) Remove the default value.
2) Enforce the default value and make all of `[energy_cap_equals, energy_cap_max, energy_cap_per_unit]` optional configs.

I'd prefer the latter. First because `inf` (= no constraint) seems a very reasonable and intuitive default to me. Second, because there are other ways of limiting the energy capacity (see #159) and it may not be obvious that one _has_ to specify both in such a case.

## Calliope version

0.6.3

**Comment by sjpfenninger** [comment]
Thanks for spotting - I agree, latter makes more sense. @brynpickering any objections to the latter option? Else I'll deal with this at some point.

**Comment by brynpickering** [comment]
Pre v0.6.0 we had everything as optional, with the defaults being able to
handle anything a user chose not to input. We moved to have 'required'
constraints so that a user has to be more explicit in setting some values,
so they know what they are and aren't caught out by our default values. I
agree that it's a bit messy to ask for explicit constraints and still have
a default value, so I would be happy with solution 2 too. It works for
`energy_cap` because we do not run that constraint over a subset of the
main loc::tech set. In almost every other instance, explicit mention of
constraint in the model configuration will create a loc::tech subset, which
then goes on to to trigger a constraint to be built in Pyomo...

**Comment by timtroendle** [comment]
I guess it depends on your perspective on what this actually is about (and the fact how it is implemented):

If, one, you assume an upper bound to energy capacity to be an additional feature (and if it actually is), making this additional feature optional is reasonable.

If, two, the constraint always exist and we are literally talking about a default value here, keeping the config mandatory seems slightly more reasonable to me.

In any case, this is not a big issue and it's probably not worth to be discussed too long. If you had thought through the whole concept before, I am absolutely fine with not making this constraint optional. But I would remove the default value in the documentation in that case.
