### ISSUE TITLE
Update docs for 0.4.0 additions

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#22]

**Comment by brynpickering** [comment]
Since changing from DataFrames to DataArrays, a number of Python interactive results analysis functions (including those found in the [Jupyter notebook](https://nbviewer.ipython.org/url/calliope.readthedocs.io/en/latest/_static/notebooks/tutorial.ipynb)) no longer seem to exist. 
E.g. the function `model.get_system_variables()` given in "running the model" is invalid. I would update docs to reflect this but have not yet tracked down the new function which would provide the same output.

**Comment by sjpfenninger** [comment]
Should be done as of  b905018
