### ISSUE TITLE
Rerun model cannot be saved as LP

### ISSUE THREAD

**Issue by timtroendle** [calliope-project/calliope#282]
## Problem description

I try to export a rerun model to LP, but that fails with a `ModelError: This model object already has results. Use model.run(force_rerun=True) to forcethe results to be overwritten with a new run.`. As this log messages stems from the `run` method, it seems `run` is falsely called within `to_lp` in this case.

## Steps to reproduce the problem

```Python
import calliope
model = calliope.examples.national_scale() # or any other model
model.run()
# optionally change model params here
new_results = model.backend.rerun()
new_results.to_lp("test.lp")
```

## Calliope version

0.6.5-dev

**Comment by timtroendle** [comment]
Workaround for myself and anyone else running into this: you can actually write the original (supposedly unchanged) model, and it will contain all your updates:

```Python
import calliope
model = calliope.examples.national_scale() # or any other model
model.run()
model.backend.update_params(...) # do updates here
model._backend_model.write("test.lp", format='lp', io_options={'symbolic_solver_labels': True})
new_results = model.backend.rerun()
```

**Comment by brynpickering** [comment]
This is because the new results are *only* a calliope model with an xarray dataset, I.e. no backend model of its own. The pyomo backend model always remains attached to the original model. After you make changes to the backend model you could also call `model.to_lp()` to save that version of the backend model to an LP file.

The question then becomes: should we also transfer across the backend model to new results on each rerun? I'm not sure it's worth it, hence why it currently isn't implemented.

**Comment by timtroendle** [comment]
What is the reason to not hand over the backend to the new model?

**Comment by brynpickering** [comment]
> What is the reason to not hand over the backend to the new model?

It's incredibly memory intensive. As a test, see below. Pyomo's ConcreteModel `clone` method is both slow and memory hungry. Running with a timeseries of 6 months made my laptop crash.
```
     3    153.8 MiB    153.8 MiB   def my_func():
     4    159.2 MiB      5.4 MiB       m = calliope.examples.national_scale()
     5    177.4 MiB     18.2 MiB       m.run()
     6    178.3 MiB      0.9 MiB       m2 = m.backend.rerun()
     7    237.6 MiB     59.3 MiB       m2._backend_model = m._backend_model.clone()
     8    237.6 MiB      0.0 MiB       return m, m2
```

The other option would be to run `m2.run(force_rerun=True, build_only=True)` internally, so that a built, but with solutions Pyomo model is attached to `m2`. But this makes the whole point of the backend interface somewhat redundant, since it is there to streamline memory and time consumption of Pyomo as much as possible. If you don't care about memory consumption, just update values in `m._model_data` and call `m.run(force_rerun=True)`.

**Comment by timtroendle** [comment]
Instead of cloning, couldn't the new model point to the same backend object of the old model? 

`m2._backend_model = m._backend_model ` performed somewhere within `m.backend.rerun()`.

**Comment by brynpickering** [comment]
Discussion continuing @ #293
