### ISSUE TITLE
simultaneous charge and discharge of storage

### ISSUE THREAD

**Issue by GlennCeusters** [calliope-project/calliope#307]
Is it normal that the storage class simultaneously charges and discharges so that the difference in power rate is "exported" to the carrier? e.g. charge 100, discharge -90 = 10 charge in carrier. I'm using the "operate" mode with calliope_version: 0.6.5

I recall from other models that, in order to avoid this, it needs a binary variable (making it a MILP).

![newplot](https://user-images.githubusercontent.com/29844834/78187269-66e91f80-746e-11ea-8e17-820d7f9c1c6a.png)

Because of these high power rates I'm unable to set a energy_cap_equals constraint.

Cheers,
/Glenn

**Comment by brynpickering** [comment]
Apologies for the delay @GlennCeusters... Yeah, it's (probably) because you have some charge/discharge inefficiency. The model uses this simultaneous charge discharge to get rid of some energy to make the energy balance feasible. You can solve that problem using a [binary variable](https://calliope.readthedocs.io/en/stable/user/advanced_constraints.html#asynchronous-energy-production-consumption).

If you don't have charge/discharge inefficiencies then it is better to just let the storage do this and remove it in your own post-processing. It doesn't hurt the 'reality' of the result, but will ensure the problem solves quicker.
