### ISSUE TITLE
Python 3.8 Vs. Calliope issues

### ISSUE THREAD

**Issue by mohammadamint** [calliope-project/calliope#327]
Hello,
Today I tried to run the model in my new laptop in which I installed the latest version of python on it.

There are some changes in the new version which makes some issues running the model.
The first one which I faced is relate to the changes in pyutilib library. In the version, pyutilib doesn't have pyutilib.enum any more while there is a separated library named enum that should be used.

While, the previous versions of python could be installed and used easily, it may worth to make the model compatible also with the new version.

Best

**Comment by timtroendle** [comment]
Thanks for the error report @mohammadamint. Python 3.8 is officially supported, so it should work. However, there is a known problem with pyutilib, which has been reported previously in #318 and fixed in #319. The fix will be part of the next release version of Calliope.

Until the fixed version is released, you can use [the workaround](https://github.com/calliope-project/calliope/issues/318#issuecomment-648747455) suggested in #318.

Can you let us know if this solves your problem?

**Comment by mohammadamint** [comment]
Thanks for your response, @timtroendle, it works with what is suggested in #318. running the install with the following command:

`conda create -n calliope -c conda-forge calliope=0.6.5 python=3.8.1 numpy=1.16.5 pandas=0.25.3 pyomo=5.6.8 pyutilib=5.7.3`
