### ISSUE TITLE
Better handling of defaults for get_option

### ISSUE THREAD

**Issue by sjpfenninger** [calliope-project/calliope#33]
Overly wordy:

        try:
            per_distance = model.get_option(y + '.per_distance')
        except: # assume one unit distance
            per_distance = 1

Something like this should be possible instead:

    per_distance = model.get_option(y + '.per_distance', 1)

See #32

**Comment by brynpickering** [comment]
So I was testing this out, it doesn't seem like the default function works properly to allow one to do that. Currently get option allows you to specify another option to search for in order to fill the default space, i.e. you would have to say `per_distance = model.get_option(y + '.per_distance', 'defaults.per_distance')` and set a per distance default in the defaults.yaml folder. I suppose that is fine to do, depends on how full we'd like the defaults.yaml file to become (we should then probably add in all the per_distance stuff)

**Comment by sjpfenninger** [comment]
``per_distance = model.get_option(y + '.per_distance')`` should be sufficient if ``'defaults.per_distance'`` is set in defaults.yaml. Perhaps that's the way it should be done, and this PR closed.

**Comment by brynpickering** [comment]
Will update PR accordingly
