### ISSUE TITLE
Installation problem Found conflict 2022

### ISSUE THREAD

**Issue by saim14** [calliope-project/calliope#378]
## terminal: conda create -c conda-forge -n calliope_alt calliope
Got the following error
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError:

**Comment by jfallon1997** [comment]
Installation also fails for me with `conda create -c conda-forge -n calliope calliope` on conda `4.12.0` with python `3.9.12` and 8GB RAM/10GB swap.

However specifying for `python=3.8` fixes this.

Also recommended to use `scikit-learn>=0.22,<0.24` as [`0.24` leads to failed clustering, due to some API change](https://github.com/calliope-project/calliope/blob/master/requirements.yml)

Could you try something like `conda create -c conda-forge -n calliope calliope=0.6.8 python=3.8 scikit-learn=0.23` and see if that fixes your installation problem?

**Comment by nit1995** [comment]
> Could you try something like `conda create -c conda-forge -n calliope calliope=0.6.8 python=3.8 scikit-learn=0.23` and see if that fixes your installation problem?

This works

**Comment by cristinaantonini** [comment]
Hi!
I'm encountering an issue when importing calliope. I've used the command above to install it (conda create -c conda-forge -n calliope calliope=0.6.8 python=3.8 scikit-learn=0.23) but when I run the model this is the error message I get:

$calliope run prova/model.yaml --save_netcdf=results.nc

Traceback (most recent call last):
  File "C:\Users\cristina.antonini\Anaconda3\envs\calliope\Scripts\calliope-script.py", line 5, in <module>
    from calliope.cli import cli
  File "C:\Users\cristina.antonini\Anaconda3\envs\calliope\lib\site-packages\calliope\__init__.py", line 3, in <module>
    from calliope import examples, exceptions  # noqa: F401
  File "C:\Users\cristina.antonini\Anaconda3\envs\calliope\lib\site-packages\calliope\examples.py", line 14, in <module>
    from calliope.core.model import Model
  File "C:\Users\cristina.antonini\Anaconda3\envs\calliope\lib\site-packages\calliope\core\__init__.py", line 1, in <module>
    from calliope.core.model import Model, read_netcdf  # noqa: F401
  File "C:\Users\cristina.antonini\Anaconda3\envs\calliope\lib\site-packages\calliope\core\model.py", line 18, in <module>
    from calliope.preprocess import (
  File "C:\Users\cristina.antonini\Anaconda3\envs\calliope\lib\site-packages\calliope\preprocess\__init__.py", line 1, in <module>
    from calliope.preprocess.model_run import (  # noqa: F401
  File "C:\Users\cristina.antonini\Anaconda3\envs\calliope\lib\site-packages\calliope\preprocess\model_run.py", line 24, in <module>
    from calliope.preprocess import nodes, checks, util

**ImportError: cannot import name 'nodes' from partially initialized module 'calliope.preprocess' (most likely due to a circular import) (C:\Users\cristina.antonini\Anaconda3\envs\calliope\lib\site-packages\calliope\preprocess\__init__.py)**

Could you please help me with this issue? Thanks!

**Comment by brynpickering** [comment]
@cristinaantonini this is a separate issue. You seem to have some conflict with the calliope version that Python is picking up. You may have a development version of calliope installed (e.g., you cloned the github repository to your local device at some point). It seems that Python is getting confused with the under-development Calliope implementation (on the github master branch) in which we have changed `locations` for `nodes`. 

Make sure your run scripts are stored separately to any calliope library code and that when working on the command line you are not accidentally working from inside or in the same directory as a library.
