### ISSUE TITLE
Default installation does not have optional dependencies

### ISSUE THREAD

**Issue by gnawin** [calliope-project/calliope#579]
### Description

I'm following the documentation to install Calliope using 
```
mamba create -n calliope -c conda-forge/label/calliope_dev -c conda-forge calliope
```

However, the installation does not come with some dependencies such as plotly or GLPK. It seems to me that they belongs to optional dependencies of the dev version, but using the above command does not install those. 

### Related links

https://calliope.readthedocs.io/en/v0.7.0.dev3/installation/

### Version

Trying to install v0.7.0 dev3

### Proposed change

Change the command so Calliope actually comes with the required dependencies.

**Comment by sjpfenninger** [comment]
Plotly is no longer a dependency because plotting is no longer part of the Calliope core. Stay tuned for a separate visualisation package to come in the next few weeks.

As for GLPK, you are correct - the documentation states that it will be installed, but that doesn't happen, so the documentation needs to be changed.

You can get glpk in the same environment by modifying the installation command like so:

`mamba create -n calliope -c conda-forge/label/calliope_dev -c conda-forge calliope glpk`

If you want plotly too:

`mamba create -n calliope -c conda-forge/label/calliope_dev -c conda-forge calliope glpk plotly`

**Comment by sjpfenninger** [comment]
The (very early stage) visualisation tool is available here now: https://github.com/calliope-project/cview
