### ISSUE TITLE
e_cap.equals=0 and e_cap.max conflict

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#63]
Hello,

I just discovered that overwriting e_cap.equals for a location isn't working with the 0 value if e_cap.max has been defined in techs.yaml. But it is working with any value above 0.

I am defining `e_cap.max: inf` in techs.yaml for a conversion_plus technology named conv_tech (the goal is to use it in different locations).
In a specific location in locations.yaml, I am overwriting e_cap.equals for that technology because the capacity if fixed at that location (but could take other values in other locations).

If I overwrite `conv_tech.constraints.e_cap.equals: 1`, the model works fine and e_cap = 1 in the simulation at that location
But if I overwrite `conv_tech.constraints.e_cap.equals: 0`, the model is giving a value different from 0 to e_cap at that location.
Finally if I overwrite `conv_tech.constraints.e_cap.max: 0`, the model works fine and e_cap = 0 in the simulation at that location.

Arnaud

**Comment by brynpickering** [comment]
Things become messy at 0 in Python! It's easy to miss it because `False` is technically `0`! There is a check [here](https://github.com/calliope-project/calliope/blob/master/calliope/constraints/base.py#L390) which is avoiding `.equals: False ` or `.equals: None` but inadvertently also avoids `.equals: 0`.

I've updated this to `if _equals is not False and _equals is not None:` in an upcoming commit which is more explicit, allowing your case to work. Of course, setting `.max` to 0 is the same as setting `.equals` to 0!

**Comment by brynpickering** [comment]
Fixed in 77a0930
