### ISSUE TITLE
Show parameter defaults and typing in the `base math` section.

### ISSUE THREAD

**Issue by irm-codebase** [calliope-project/calliope#677]
### Description

We should show the default values in the default math section.

These are surprisingly hard to find without directly going to the code, which is probably now what we want users to do.

![image](https://github.com/user-attachments/assets/231b1367-ba3a-414b-b125-bb8a30e777e6)

### Related links

- https://calliope.readthedocs.io/en/latest/math/base/
- https://calliope.readthedocs.io/en/latest/reference/model_schema/

### Version

v0.7.0

### Proposed change

Show the default in the base-math section.

I think `ruff` does it in a particularly nice way https://docs.astral.sh/ruff/settings/#extend
They show the default and the type of the variable. I do not think we need to add examples, though.

**Comment by brynpickering** [comment]
Good to see you recommend the `ruff` approach, because that's exactly what we do (without even knowing `ruff` does it)! See e.g. one of our [decision variables](https://calliope.readthedocs.io/en/latest/math/base/#area_use). Parameter defaults should also be making their way through. Will need to investigate where they're getting lost.

**Comment by irm-codebase** [comment]
Huh, I missed that decision variables had it...
So yeah, pretty much that, but for parameters!
