### ISSUE TITLE
Operate mode in 0.5.3

### ISSUE THREAD

**Issue by arnaud-leroy** [calliope-project/calliope#68]
Hi,
I am mostly using plan mode but I just wanted to say that operate mode isn't working in 0.5.3 version for models which were working on the previous version.

This is the error message:
ERROR:pyomo.core:Rule failed when generating expression for constraint c_e_cap with index ('unmet_demand_he_at2', 'L1'):
ModelError: Cannot use inf, NaN, or None in operational mode, for value of unmet_demand_he_at2.e_cap.max.L1
ERROR:pyomo.core:Constructing component 'c_e_cap' from data=None failed:
ModelError: Cannot use inf, NaN, or None in operational mode, for value of unmet_demand_he_at2.e_cap.max.L1

**Comment by sjpfenninger** [comment]
Thanks - we'll investigate

**Comment by brynpickering** [comment]
Hi Arnaud,

Partially not a bug. It shouldn't trigger for unmet_demand, but is otherwise a necessity to ensure that operational mode will actually function correctly. You need to have set _all_ capacity constraints to finite values, otherwise during optimisation the constraints allow a technology's capacity to vary on each iteration of the rolling horizon (which is clearly erroneuous). We'll update it to not cover unmet_demand, but for now you can just set an `e_cap.max` for unmet_demand that is some finite, large value.
