### ISSUE TITLE
Issue when 'r' is input as time-series. In operate mode.

### ISSUE THREAD

**Issue by csv2000** [calliope-project/calliope#70]
While running in operate mode, changes made to the input resource csv file containing the resource availability of csp in the example model do not get reflected in the solution.  Details of the run are below.

We ran the example model present in the package version 0.5.2  in 'operate' mode. 
The time slice was 5 days (1st Jan to 5th Jan). 
Trials were done with and without the constraint force_r: true. 
Different values of resource in file csp_r.csv were tried (listed below)
1. 50% of original input
2. All non-zero values in original csv file were set to 1
3. All zeros values in original csv file were set to 1 and non-zeros to 0.

The model was solved with both glpk and gurobi.

In all cases the output summary showed e_prod of around 8.9e5 and cf of around 0.27. The production curve also did not show much difference.

Also the total e_prod calculated from the csv file (after efficiency) for these days did not tally with the e_prod in the summary with and without force_r. Thats a violation of the conservation constraint.

**Comment by brynpickering** [comment]
I'll need more information about the model you created in order to troubleshoot this. Perhaps you could create a Gist with the yaml files?
Operational mode is not at its best at the moment though. I expect that it is a problem on this end that will lead to us taking it down for the time being, until we have reconstructed the backend!

**Comment by csv2000** [comment]
We first ran our model and later tried the example national model. I have mailed you the yaml files of the example model we tried.

**Comment by brynpickering** [comment]
I've taken a look through what you sent. This feeds into issues #29 and #68. Basically, you can't run operational mode without all capacities being known. Your model has 'inf' for certain maximum capacities, which leads to each new iteration (each 24 hr period in your case) reassigning a technology's capacity, because there is no constraint telling it to be _exactly_ some value. in v0.5.3, not setting all values leads to the model generation failing.

There are two approaches: 

1. set all `.max` or `.equals` capacities to a finite value that you think is reasonable (for csp this is `r_cap.max`, `e_cap.max`, and `r_area.max`, although there are constraints which link them: `r_area_per_e_cap` and `r_cap_equals_e_cap`). 

2. run the problem in operational mode, then take the resulting `r_cap`, `s_cap`, `e_cap`, and `r_area` values and reinsert them by either typing them into the yaml files or by using e.g. `model.set_option(y +'.constraints.e_cap.equals', model.solution.e_cap.loc[dict(y=y, x=x)].values, x=x) for x in locations for y in technologies `

In the long run we should require different model files for operational mode, then ignore investment decision variables, constraints, and costs.

**Comment by csv2000** [comment]
Thanks, setting the max capacities seems to fix the problem of reflecting the resource in csv file in the final solution. I still have to verify the generation output numbers and cf in the solution. 

Approach 1 is  tricky as any large number for capacity upper bound cannot be used as the solver renders it as unbound. So replacing 'inf' with #FFFF (largest number) is not an option. In approach 2 (I guess you mean first run in plan mode), using 'plan' mode solution  does not allow user to force pre-defined behaviour for particular techs in operation..   

This trial was on the example national model shared in the calliope package. Perhaps an example in the operate mode can be added to the package.

**Comment by sjpfenninger** [comment]
In 0.6.0 operational mode capacities are no long decision variables, but parameters, and Calliope automatically determines which of these need to be finite (e.g. generation and conversion technologies).
