### ISSUE TITLE
'-' character is no longer supported in a technology name

### ISSUE THREAD

**Issue by jmorrisnrel** [calliope-project/calliope#708]
### What happened?

v0.6.x supported `-` in a technology name which we used as an optional delimiter in the name for organizing technologies. In v0.7, the regex validation for tech name fails with a `-`. 
`Errors during validation of the Model definition dictionary.:\n * techs: 'Test-Test' does not match any of the regexes: '^[^_^\\\\d][\\\\w]*$'`

We can adjust our delimiter if the change was intentional but wanted to flag it in case it was not.

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [X] Linux

### Version

v0.7.0.dev3

**Comment by brynpickering** [comment]
It was intentional, to force all user-defined keys to be pythonic. I.e., no starting with a number and no symbols allowed except `_`. This allows everything to be referenced as attributes in the calliope AttrDict (e.g. `techs.my_tech` works but `techs.my-tech` doesn't), which can be useful when writing python scripts that have calliope as a dependency.
