### ISSUE TITLE
Suppress blank values when using csv as output file format

### ISSUE THREAD

**Issue by GraemeHawker** [calliope-project/calliope#83]
As csv format does not compress zero values efficiently, some files (e.g. solution.e) can be many gb in size for models of high dimensionality, which makes them practically unusable for the purposes that csv output might be used for (e.g. manual checking in Excel)

**Comment by brynpickering** [comment]
We should have this sorted in 0.6.0, as almost all superfluous decision variables don't crop up or are NaN (and can be easily removed before saving to CSV). Difficult to remove in 0.5.x because we may not be able to differentiate between a zero value that is meant to be there and one that indicates the location-technology-carrier combination is superfluous.

**Comment by sjpfenninger** [comment]
@GraemeHawker in 0.6.0 (now in the `master` branch), we have implemented `Model.to_csv('/path/to/save/to')` -- can you check whether this resolves your issue?
